name: Prepare Kaggle Export
on:
  workflow_dispatch:
jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: pip install -r requirements.txt
      - name: Prep dataset bundle
        run: python scripts/prep_kaggle_export.py
      - name: Archive data
        run: zip -r kaggle_data_bundle.zip data
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: kaggle_data_bundle
          path: kaggle_data_bundle.zip
