name: CI / Pipeline smoke test

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    inputs:
      region:
        description: 'Region to run (use sample like "jamaica_coffee")'
        required: true
        default: 'jamaica_coffee'

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Cache pip
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt || true
        pip install -e . || true

    - name: Run pipeline smoke test
      env:
        OFFLINE_MODE: "1"
      run: |
        REGION="${{ github.event.inputs.region || 'jamaica_coffee' }}"
        echo "Running smoke test for region: $REGION"
        python scripts/run_pipeline.py --region "$REGION" --insight --dry-run || echo "Pipeline exited non-zero"

    - name: Upload outputs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: pipeline-outputs
        path: |
          outputs/**
          logs/**
